@startuml erd

left to right direction

entity user as "ユーザー" {
    + id [PK]
    --
    name [ユーザー名]
    email_address [メールアドレス]
    password_hash [パスワードハッシュ]
    access_token [アクセストークンの秘密鍵]
}

entity follow as "フォロー" {
    + id [PK]
    --
}

entity follower as "フォロワー" {
    + id [PK]
    --
}

entity block as "ブロックユーザー" {
    + id [PK]
    --
}

entity mute as "ミュートユーザー" {
    + id [PK]
    --
}

entity signup_access_token as "サインアップ用\nアクセストークン" {
    + id [PK]
    --
    access_token [アクセストークン]
    secret_key [秘密鍵]
}

entity post as "投稿" {
    + id [PK]
    --
    text [文章]
    created at [初回投稿日時]
    updated at [最終更新日時]
}

entity comment as "投稿コメント" {
    + id [PK]
    --
    text [文章]
    created at [初回投稿日時]
    updated at [最終更新日時]
}

entity good as "いいね" {
    + id [PK]
    --
    datetime [日時]
}

entity empathy as "共感" {
    + id [PK]
    --
    datetime [日時]
}

entity collect as "お気に入り" {
    + id [PK]
    --
    datetime [日時]
}

entity icon as "アカウント用アイコン" {
    + id [PK]
    --
    color [背景色]
}

user ||--o{ post
user ||--|| icon
user ||--o{ follow
user ||--o{ follower
user ||--o{ block
user ||--o{ mute
user ||--o{ good
user ||--o{ empathy
user ||--o{ collect

post ||--o{ comment
post ||--o{ good
post ||--o{ empathy
post ||--o{ collect

comment ||--o{ good
comment ||--o{ empathy
comment ||--o{ collect

@enduml
