services:
  lite-sns-devenvs:
    image: whoatemyapplepie/lite-sns-devenvs:1.0.0
    build:
      context: .
    container_name: lite-sns-devenvs
    ports:
      - 8080:8080
    volumes:
      - ../:/project
    tty: true
