services:
  lite-sns-devenvs:
    image: whoatemyapplepie/lite-sns-devenvs:1.0.0
    build:
      context: .
    container_name: lite-sns-devenvs
    ports:
      - 18080:18080
      - 18081:18081
    volumes:
      - ../:/project
    tty: true
