services:
  lite-sns-devenvs:
    image: whoatemyapplepie/lite-sns-devenvs:1.0.0
    build:
      context: .
      args:
        - WEB_SERVER_PORT=${WEB_SERVER_PORT}
        - APP_SERVER_PORT=${APP_SERVER_PORT}
    container_name: lite-sns-devenvs
    ports:
      - ${WEB_SERVER_PORT}:${WEB_SERVER_PORT}
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ../:/project
    tty: true
    networks:
      default:
      lite-sns-net:
        ipv4_address: ${APP_SERVER_IP}
  db:
    image: postgres:17.0-alpine3.20
    restart: always
    shm_size: 128mb
    container_name: lite-sns-db
    ports:
      - ${DB_SERVER_PORT}:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
    networks:
      lite-sns-net:
        ipv4_address: ${DB_SERVER_IP}
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      default:
      lite-sns-net:
        ipv4_address: ${ADMINER_IP}

networks:
  default:
  lite-sns-net:
    name: lite-sns-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${LITE_SNS_SUBNET}
