services:
  lite-sns-devenvs:
    image: whoatemyapplepie/lite-sns-devenvs:1.0.0
    build:
      context: .
      args:
        - WEB_SERVER_PORT=${WEB_SERVER_PORT}
        - APP_SERVER_PORT=${APP_SERVER_PORT}
    container_name: lite-sns-devenvs
    ports:
      - ${WEB_SERVER_PORT}:${WEB_SERVER_PORT}
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ../:/project
    tty: true
  db:
    image: postgres:17.0-alpine3.20
    restart: always
    shm_size: 128mb
    container_name: lite-sns-db
    ports:
      - ${DB_SERVER_PORT}:${DB_SERVER_PORT}
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
